jjltech/apps/accounts/urls.py
# Urls.py file for accounts app
from django.urls import path
from .views import login_view, logout_view, home_view, sign_up, view_profile, edit_profile

app_name = 'accounts'
urlpatterns = [
    path('', home_view, name='home'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('sign_up/', sign_up, name='signup'),
    path('profile/', view_profile, name='view_profile'),
    path('profile/edit/', edit_profile, name='edit_profile')
]

jjltech/apps/core/urls.py
from django.urls import path
from .views import dashboard_view, index_view


app_name = 'core'

urlpatterns = [
    path('', index_view, name='index'),
    path('dashboard/', dashboard_view, name='dashboard'),

   
]

jjltech/apps/pitchdeck/urls.py
from django.urls import path
from .views import create_pitch_view, edit_pitch_view, pitchdeck_detail_view, pitchdeck_board 
from .views import like_pitch, pitchdeck_view

app_name = 'pitchdeck'

urlpatterns = [
    path('create/', create_pitch_view, name='create'),
    path('edit/', edit_pitch_view, name='edit'),
    path('detail/', pitchdeck_detail_view, name='detail'),
    path('board/', pitchdeck_board, name='board'),
    path('like/<int:pitch_id>/', like_pitch, name='like_pitch'),
    path('view/<int:pitch_id>/', pitchdeck_view, name='pitchdeck_view')
]

jjltech/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pitchdeck/', include('jjltech.apps.pitchdeck.urls')),
    path('accounts/', include('jjltech.apps.accounts.urls')),
    path('', include('jjltech.apps.core.urls')),
]

if settings.DEBUG:
    urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jjltech/apps/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django_countries.fields import CountryField
import os
import logging

logger = logging.getLogger(__name__)

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    country = CountryField(blank_label='(select country)', default='NG')
    headline = models.CharField(max_length=150, blank=True)
    profile_image = models.ImageField(upload_to='profile_pics/', blank=True)
    bio = models.TextField(max_length=1000, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        logger.info(f"Saving profile for user: {self.user.username}")
        try:
            if self.profile_image:
                # Get the file extension
                ext = os.path.splitext(self.profile_image.name)[1]
                # Rename the file to the user's username
                new_filename = f"{self.user.username}{ext}"
                # Save the file with the new name - include the folder!
                self.profile_image.name = f"profile_pics/{new_filename}"

                print(f"Saving file to: {self.profile_image.name}")

            super().save(*args, **kwargs)
        except Exception as e:
            logger.error(f"Error saving profile image: {e}")
            raise

    def __str__(self):
        return f"{self.user.username}'s Profile"

jjltech/apps/core/models.py
from django.db import models

# Create your models here.

jjltech/apps/pitchdeck/models.py
from django.db import models
from django.contrib.auth.models import User

class PitchDeck(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    pitch = models.TextField(max_length=7000)
    instagram = models.URLField(max_length=200, blank=True, null=True)
    linkedin = models.URLField(max_length=200, blank=True, null=True)
    website = models.URLField(max_length=200, blank=True,  null=True)
    twitter = models.URLField(max_length=200, blank=True, null=True)
    facebook = models.URLField(max_length=200, blank=True, null=True)
    youtube = models.URLField(max_length=200, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    likes = models.ManyToManyField(User, related_name='liked_pitches', blank=True)
    clicks = models.PositiveIntegerField(default=0)
    INDUSTRY_CHOICES = [
        ('tech', 'Technology'),
        ('finance', 'Finance'),
        ('health', 'Healthcare'),
        ('education', 'Education'),
        ('entertainment', 'Entertainment'),
        ('retail', 'Retail'),
        ('manufacturing', 'Manufacturing'),
        ('real_estate', 'Real Estate'),
        ('transportation', 'Transportation'),
        ('energy', 'Energy'),
        ('agriculture', 'Agriculture'),
        ('hospitality', 'Hospitality'),
        ('construction', 'Construction'),
        ('legal', 'Legal'),
        ('marketing', 'Marketing'),
        ('media', 'Media'),
        ('non_profit', 'Non-Profit'),
        ('sports', 'Sports'),
        ('telecommunications', 'Telecommunications'),
        ('utilities', 'Utilities'),
        ('other', 'Other'),
    ]
    industry = models.CharField(max_length=100, choices=INDUSTRY_CHOICES, blank=True)

    def __str__(self):
        return f"{self.user.username}'s PitchDeck"

jjltech/apps/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django_countries.widgets import CountrySelectWidget
from django_countries.fields import CountryField
from .models import Profile

class LoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Username",
                "class": "form-control"
            }
        ))
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Password",
                "class": "form-control"
            }
        ))

class SignUpForm(UserCreationForm):
    email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={'class': 'form-control'}))
    first_name = forms.CharField(required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    country = CountryField(blank_label='(Select Country)').formfield(
        widget=CountrySelectWidget(attrs={'class': 'form-control form-select'})
    )
    headline = forms.CharField(required=False, widget=forms.TextInput(attrs={'class': 'form-control'}))
    bio = forms.CharField(required=False, widget=forms.Textarea(attrs={'class': 'form-control'}))

    class Meta:
        model = get_user_model()
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2', 'country', 'headline', 'bio')
        help_texts = {
            'username': None,
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'class': 'form-control'})
        if 'password2' in self.fields:
            self.fields['password2'].widget = forms.PasswordInput(attrs={'class': 'form-control'})
        self.fields['password2'].label = "Confirm Password"
        self.fields['password2'].help_text = None
        self.fields['password1'].widget = forms.PasswordInput(attrs={'class': 'form-control'})
        self.fields['password1'].label = "Password"
        self.fields['password1'].help_text = None

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['country', 'headline', 'profile_image', 'bio']
        widgets = {
            'country': CountrySelectWidget(attrs={'class': 'form-control form-select'}),
            'headline': forms.TextInput(attrs={'class': 'form-control'}),
            'profile_image': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'bio': forms.Textarea(attrs={'class': 'form-control'}),
        }

jjltech/apps/pitchdeck/forms.py
# jjltech/apps/pitchdeck/forms.py
from django import forms
from .models import PitchDeck

class PitchDeckForm(forms.ModelForm):
    class Meta:
        model = PitchDeck
        fields = ('pitch', 'industry', 'instagram', 'linkedin', 'website', 'twitter', 'facebook', 'youtube')
        # widgets = {
        #     'pitch': forms.Textarea(attrs={'rows': 6, 'placeholder': 'Pitch'}),
        #     'industry': forms.Select(attrs={'placeholder': 'Industry'}),
        #     'instagram': forms.TextInput(attrs={'placeholder': 'Instagram URL'}),
        #     'linkedin': forms.TextInput(attrs={'placeholder': 'LinkedIn URL'}),
        #     'website': forms.URLInput(attrs={'placeholder': 'Website URL'}),
        #     'twitter': forms.TextInput(attrs={'placeholder': 'Twitter URL'}),
        #     'facebook': forms.TextInput(attrs={'placeholder': 'Facebook URL'}),
        #     'youtube': forms.TextInput(attrs={'placeholder': 'YouTube URL'}),
        # }

jjltech/apps/accounts/views.py
# Create your views here.
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth import logout
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from .forms import LoginForm, SignUpForm, ProfileForm
from .models import Profile


def home_view(request):
    return HttpResponseRedirect(reverse('accounts:login'))

def login_view(request):
    form = LoginForm(request.POST or None)

    msg = None

    if request.method == "POST":

        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect("core:dashboard")
            else:
                msg = 'Invalid credentials'
        else:
            msg = 'Error validating the form'

    return render(request, "accounts/login.html", {"form": form, "msg": msg})

def logout_view(request):
    logout(request)
    return redirect('accounts:login')


def sign_up(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save(commit=False)
            user.first_name = form.cleaned_data.get('first_name')
            user.last_name = form.cleaned_data.get('last_name')
            user.email = form.cleaned_data.get('email')
            user.save()

            # Create the profile
            Profile.objects.create(
                user=user,
                country=form.cleaned_data.get('country'),
                headline=form.cleaned_data.get('headline'),
                bio=form.cleaned_data.get('bio'),
            )

            messages.success(request, 'Kindly Login to your Account.')
            return redirect('accounts:login')
        else:
            messages.error(request, 'There was an error creating the user.')
    else:
        form = SignUpForm()
    return render(request, 'accounts/signup.html', {'form': form})


@login_required
def view_profile(request):
    user = request.user
    context = {
        'user': user,
    }
    return render(request, 'accounts/view_profile.html', context)


@login_required
def edit_profile(request):
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=request.user.profile)
        if form.is_valid():
            form.save()
            return redirect('accounts:view_profile')
    else:
        form = ProfileForm(instance=request.user.profile)

    context = {
        'form': form,
    }
    return render(request, 'accounts/edit_profile.html', context)

jjltech/apps/core/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from jjltech.apps.pitchdeck.models import PitchDeck
from django.db.models import Q

def index_view(request):
    return render(request, 'core/website/index.html')
    
@login_required
def dashboard_view(request):

    user = request.user
    pitchdeck = PitchDeck.objects.filter(user=user).first()
    total_users = User.objects.count()
    same_country_users = User.objects.filter(profile__country=user.profile.country).count()
    same_industry_users = PitchDeck.objects.filter(industry=pitchdeck.industry).count() if pitchdeck else 0

    context = { 

        'user': user,
        'pitchdeck': pitchdeck,
        'total_users': total_users,
        'same_country_users': same_country_users,
        'same_industry_users': same_industry_users,
    }
    return render(request, 'core/dashboard.html', context)

jjltech/apps/pitchdeck/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from .models import PitchDeck
from .forms import PitchDeckForm
from django.db.models import Q
from django.core.paginator import Paginator
from django.http import JsonResponse
from django_countries import countries

# Options for Industry Choices
INDUSTRY_CHOICES = [
        ('tech', 'Technology'),
        ('finance', 'Finance'),
        ('health', 'Healthcare'),
        ('education', 'Education'),
        ('entertainment', 'Entertainment'),
        ('retail', 'Retail'),
        ('manufacturing', 'Manufacturing'),
        ('real_estate', 'Real Estate'),
        ('transportation', 'Transportation'),
        ('energy', 'Energy'),
        ('agriculture', 'Agriculture'),
        ('hospitality', 'Hospitality'),
        ('construction', 'Construction'),
        ('legal', 'Legal'),
        ('marketing', 'Marketing'),
        ('media', 'Media'),
        ('non_profit', 'Non-Profit'),
        ('sports', 'Sports'),
        ('telecommunications', 'Telecommunications'),
        ('utilities', 'Utilities'),
        ('other', 'Other'),
    ]


def create_pitch_view(request):
    if request.method == 'POST':
        form = PitchDeckForm(request.POST)
        if form.is_valid():
            pitch = form.save(commit=False)
            pitch.user = request.user
            pitch.save()
            return redirect('pitchdeck:detail')
    else:
        form = PitchDeckForm()
    return render(request, 'pitchdeck/create.html', {'form': form})

def edit_pitch_view(request):
    user = request.user
    pitch = PitchDeck.objects.filter(user=user).first()
    if request.method == 'POST':
        form = PitchDeckForm(request.POST, instance=pitch)
        if form.is_valid():
            pitch = form.save(commit=False)
            pitch.user = request.user
            pitch.save()
            return redirect('pitchdeck:detail')
    else:
        form = PitchDeckForm(instance=pitch)
    return render(request, 'pitchdeck/edit.html', {'form': form})

def pitchdeck_detail_view(request):
    user = request.user
    pitch = PitchDeck.objects.filter(user=user).first()
    return render(request, 'pitchdeck/detail.html', {'pitch': pitch})

def pitchdeck_board(request):
    # get country choices from the country fields module
    country_choices = countries
    # get industry choices from the PitchDeck model
    industry_choices = INDUSTRY_CHOICES
    pitchdecks = PitchDeck.objects.all()
    # get top pitches, pitches with highest likes
    top_pitches = pitchdecks.order_by('-likes')[:5]
    industry = request.GET.get('industry')
    country = request.GET.get('country')
    keywords = request.GET.get('keywords')

    if industry:
        pitchdecks = pitchdecks.filter(industry=industry)
    if country:
        pitchdecks = pitchdecks.filter(user__profile__country=country)
    if keywords:
        pitchdecks = pitchdecks.filter(
            Q(pitch__icontains=keywords)
        )

    # Paginate the pitchdecks
    paginator = Paginator(pitchdecks, 12)  # Show 12 pitches per page
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'country_choices': country_choices,
        'industry_choices': industry_choices,
        'top_pitches': top_pitches,
        'industry': industry,
        'country': country,
        'keywords': keywords,
    }
    return render(request, 'pitchdeck/pitchdeck_board.html', context)


def like_pitch(request, pitch_id):
    pitch = get_object_or_404(PitchDeck, id=pitch_id)
    if request.user in pitch.likes.all():
        pitch.likes.remove(request.user)
        liked = False
    else:
        pitch.likes.add(request.user)
        liked = True
    return JsonResponse({'liked': liked, 'likes_count': pitch.likes.count()})


def pitchdeck_view(request, pitch_id):
    pitch = get_object_or_404(PitchDeck, id=pitch_id)
    pitch.clicks += 1
    pitch.save()

    # Fetch similar pitches based on industry or country
    similar_pitches = PitchDeck.objects.filter(
        Q(industry=pitch.industry) | Q(user__profile__country=pitch.user.profile.country)
    ).exclude(id=pitch.id)[:5]  # Exclude the current pitch and limit to 5

    context = {
        'pitch': pitch,
        'similar_pitches': similar_pitches,
    }
    return render(request, 'pitchdeck/pitchdeck.html', context)

jjltech/templates/includes/fixed-plugin.html
  <div class="fixed-plugin">
    <div class="dropdown show-dropdown">
      <a href="#" data-toggle="dropdown">
        <i class="fa fa-cog fa-2x"> </i>
      </a>
      <ul class="dropdown-menu">
        <li class="header-title"> Sidebar Filters</li>
        <li class="adjustments-line">
          <a href="javascript:void(0)" class="switch-trigger active-color">
            <div class="badge-colors ml-auto mr-auto">
              <span class="badge filter badge-purple" data-color="purple"></span>
              <span class="badge filter badge-azure" data-color="azure"></span>
              <span class="badge filter badge-green" data-color="green"></span>
              <span class="badge filter badge-warning" data-color="orange"></span>
              <span class="badge filter badge-danger" data-color="danger"></span>
              <span class="badge filter badge-rose active" data-color="rose"></span>
            </div>
            <div class="clearfix"></div>
          </a>
        </li>
        <li class="header-title">Images</li>
        <li class="active">
          <a class="img-holder switch-trigger" href="javascript:void(0)">
            <img src="/static/assets/img/sidebar-1.jpg" alt="">
          </a>
        </li>
        <li>
          <a class="img-holder switch-trigger" href="javascript:void(0)">
            <img src="/static/assets/img/sidebar-2.jpg" alt="">
          </a>
        </li>
        <li>
          <a class="img-holder switch-trigger" href="javascript:void(0)">
            <img src="/static/assets/img/sidebar-3.jpg" alt="">
          </a>
        </li>
        <li>
          <a class="img-holder switch-trigger" href="javascript:void(0)">
            <img src="/static/assets/img/sidebar-4.jpg" alt="">
          </a>
        </li>
        {% comment %} <li class="button-container">
          <a target="_blank" rel="noopener noreferrer"
             href="https://appseed.us/admin-dashboards" class="btn btn-default btn-block">
             More Templates
          </a>
        </li>
        <li class="button-container">
          <a target="_blank" rel="noopener noreferrer" 
             href="https://appseed.us" class="btn btn-primary btn-block">
             AppSeed
          </a>
        </li> {% endcomment %}
      </ul>
    </div>
  </div>

jjltech/templates/includes/footer.html
    <footer class="footer">
        <div class="container-fluid">
          <nav class="float-left">
            <ul>

              <li>
                <a target="_blank" rel="noopener noreferrer" 
                   href="https://appseed.us/admin-dashboards/django-dashboard-material">
                   PitchDeck 
                </a>
              </li>

            </ul>
          </nav>
          <div class="copyright float-right">
            &copy; <a target="_blank" rel="noopener noreferrer" 
                      href="https://bit.ly/3fKQZaL">Creative Tim AppSeed</a> 
                      - coded by <a target="_blank" rel="noopener noreferrer" href="https://johnjaylawal.me">John J. Lawal</a>
          </div>
        </div>
    </footer>

jjltech/templates/includes/navigation-rtl.html
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
        <div class="container-fluid">
          <div class="navbar-wrapper">
            <a class="navbar-brand" href="#pablo">داشبورد</a>
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="sr-only">Toggle navigation</span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
          </button>

          <div class="collapse navbar-collapse justify-content-end">
            <form class="navbar-form">
              <div class="input-group no-border">
                <input type="text" value="" class="form-control" placeholder="Search...">
                <button type="submit" class="btn btn-white btn-round btn-just-icon">
                  <i class="material-icons">search</i>
                  <div class="ripple-container"></div>
                </button>
              </div>
            </form>
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="#pablo">
                  <i class="material-icons">dashboard</i>
                  <p class="d-lg-none d-md-block">
                    آمارها
                  </p>
                </a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="material-icons">notifications</i>
                  <span class="notification">5</span>
                  <p class="d-lg-none d-md-block">
                    اعلان‌ها
                  </p>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="#">محمدرضا به ایمیل شما پاسخ داد</a>
                  <a class="dropdown-item" href="#">شما ۵ وظیفه جدید دارید</a>
                  <a class="dropdown-item" href="#">از حالا شما با علیرضا دوست هستید</a>
                  <a class="dropdown-item" href="#">اعلان دیگر</a>
                  <a class="dropdown-item" href="#">اعلان دیگر</a>
                </div>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link" href="#pablo" id="navbarDropdownProfile" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="material-icons">person</i>
                  <p class="d-lg-none d-md-block">
                    Account
                  </p>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownProfile">
                  <a class="dropdown-item" href="/page-user.html">Profile</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'logout' %}" >Log out</a>
                </div>
              </li>
            </ul>
          </div>

        </div>
      </nav>

jjltech/templates/includes/navigation.html
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
  <div class="container-fluid">
      <div class="navbar-wrapper">
          <a class="navbar-brand" href="#pablo">Welcome to PITCHDECK</a>
      </div>
      <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
          <span class="sr-only">Toggle navigation</span>
          <span class="navbar-toggler-icon icon-bar"></span>
          <span class="navbar-toggler-icon icon-bar"></span>
          <span class="navbar-toggler-icon icon-bar"></span>
      </button>

      <div class="collapse navbar-collapse justify-content-end">
          {% if request.user.is_authenticated %}
          <ul class="navbar-nav">
              {% if messages %}
              {% for message in messages %}
              <li class="nav-item">
                  <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                      {{ message }}
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                      </button>
                  </div>
              </li>
              {% endfor %}
              {% endif %}
              <li class="nav-item dropdown">
                  <a class="nav-link" href="#pablo" id="navbarDropdownProfile" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <i class="material-icons">person</i>
                      <p class="d-lg-none d-md-block">
                          Account
                      </p>
                  </a>
                  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownProfile">
                    <a class="dropdown-item" href="{% url 'accounts:view_profile' %}">My Profile</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'accounts:logout' %}">Log out</a>
                </div>
              </li>
          </ul>
          {% endif %}
      </div>
  </div>
</nav>

jjltech/templates/includes/sidebar.html
<div class="sidebar" data-color="purple" data-background-color="white" data-image="/static/assets/img/sidebar-1.jpg">
  <div class="logo">
    <a target="_blank" rel="noopener noreferrer" 
       href="{% url 'core:dashboard' %}" class="simple-text logo-normal">
      PITCHDECK
    </a>
  </div>
  <div class="sidebar-wrapper">
    <ul class="nav">
      {% if request.user.is_authenticated %}
        <li class="nav-item {% if 'dashboard' in request.path %} active {% endif %}">
          <a class="nav-link" href="{% url 'core:dashboard' %}">
            <i class="material-icons">dashboard</i>
            <p>Dashboard</p>
          </a>
        </li>
        <li class="nav-item {% if 'profile' in request.path %} active {% endif %}">
          <a class="nav-link" data-toggle="collapse" href="#profileMenu" aria-expanded="false">
            <i class="material-icons">person</i>
            <p>Profile</p>
          </a>
          <div class="collapse" id="profileMenu">
            <ul class="nav">
              <li class="nav-item {% if 'view-profile' in request.path %} active {% endif %}">
                <a class="nav-link" href="{% url 'accounts:view_profile' %}">
                  <i class="material-icons">visibility</i>
                  <p>View Profile</p>
                </a>
              </li>
              <li class="nav-item {% if 'edit-profile' in request.path %} active {% endif %}">
                <a class="nav-link" href="{% url 'accounts:edit_profile' %}">
                  <i class="material-icons">edit</i>
                  <p>Edit Profile</p>
                </a>
              </li>
            </ul>
          </div>
        </li>
        <li class="nav-item {% if 'pitchdeck' in request.path %} active {% endif %}">
          <a class="nav-link" data-toggle="collapse" href="#pitchdeckMenu" aria-expanded="false">
            <i class="material-icons">assignment</i>
            <p>PitchDeck</p>
          </a>
          <div class="collapse" id="pitchdeckMenu">
            <ul class="nav">
                {% if pitchdeck %}

                {% else %}
                  <li class="nav-item {% if 'create-pitchdeck' in request.path %} active {% endif %}">
                    <a class="nav-link" href="{% url 'pitchdeck:create' %}">
                      <i class="material-icons">add</i>
                      <p>Create PitchDeck</p>
                    </a>
                  </li>
                {% endif %}
                <li class="nav-item {% if 'detail-pitchdeck' in request.path %} active {% endif %}">
                <a class="nav-link" href="{% url 'pitchdeck:detail' %}">
                  <i class="material-icons">visibility</i>
                  <p>View PitchDeck</p>
                </a>
                </li>
              
              <li class="nav-item {% if 'edit-pitchdeck' in request.path %} active {% endif %}">
                <a class="nav-link" href="{% url 'pitchdeck:edit' %}">
                  <i class="material-icons">edit</i>
                  <p>Edit PitchDeck</p>
                </a>
              </li>
              <li class="nav-item {% if 'pitchdeck-board' in request.path %} active {% endif %}">
                <a class="nav-link" href="{% url 'pitchdeck:board' %}">
                  <i class="material-icons">dashboard</i>
                  <p>PitchDeck Board</p>
                </a>
              </li>
            </ul>
          </div>
        </li>
        <li class="nav-item ">
          <a class="nav-link" href="{% url 'accounts:logout' %}">
            <i class="material-icons">directions_run</i>
            <p>Logout</p>
          </a>
        </li>
      {% else %}
        <!-- Add any links for non-authenticated users if needed -->
      {% endif %}
    </ul>
  </div>
</div>