jjltech/apps/pitchdeck/urls.py
from django.urls import path
from .views import create_pitch_view, edit_pitch_view, pitchdeck_detail_view, pitchdeck_board 
from .views import like_pitch, pitchdeck_view

app_name = 'pitchdeck'

urlpatterns = [
    path('create/', create_pitch_view, name='create'),
    path('edit/', edit_pitch_view, name='edit'),
    path('detail/', pitchdeck_detail_view, name='detail'),
    path('board/', pitchdeck_board, name='board'),
    path('like/<int:pitch_id>/', like_pitch, name='like_pitch'),
    path('view/<int:pitch_id>/', pitchdeck_view, name='pitchdeck_view')
]

jjltech/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pitchdeck/', include('jjltech.apps.pitchdeck.urls')),
    path('accounts/', include('jjltech.apps.accounts.urls')),
    path('', include('jjltech.apps.core.urls')),
]

if settings.DEBUG:
    urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jjltech/apps/pitchdeck/models.py
from django.db import models
from django.contrib.auth.models import User

class PitchDeck(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    pitch = models.TextField(max_length=7000)
    instagram = models.URLField(max_length=200, blank=True, null=True)
    linkedin = models.URLField(max_length=200, blank=True, null=True)
    website = models.URLField(max_length=200, blank=True,  null=True)
    twitter = models.URLField(max_length=200, blank=True, null=True)
    facebook = models.URLField(max_length=200, blank=True, null=True)
    youtube = models.URLField(max_length=200, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    likes = models.ManyToManyField(User, related_name='liked_pitches', blank=True)
    clicks = models.PositiveIntegerField(default=0)
    INDUSTRY_CHOICES = [
        ('tech', 'Technology'),
        ('finance', 'Finance'),
        ('health', 'Healthcare'),
        ('education', 'Education'),
        ('entertainment', 'Entertainment'),
        ('retail', 'Retail'),
        ('manufacturing', 'Manufacturing'),
        ('real_estate', 'Real Estate'),
        ('transportation', 'Transportation'),
        ('energy', 'Energy'),
        ('agriculture', 'Agriculture'),
        ('hospitality', 'Hospitality'),
        ('construction', 'Construction'),
        ('legal', 'Legal'),
        ('marketing', 'Marketing'),
        ('media', 'Media'),
        ('non_profit', 'Non-Profit'),
        ('sports', 'Sports'),
        ('telecommunications', 'Telecommunications'),
        ('utilities', 'Utilities'),
        ('other', 'Other'),
    ]
    industry = models.CharField(max_length=100, choices=INDUSTRY_CHOICES, blank=True)

    def __str__(self):
        return f"{self.user.username}'s PitchDeck"

jjltech/apps/pitchdeck/forms.py
# jjltech/apps/pitchdeck/forms.py
from django import forms
from .models import PitchDeck

class PitchDeckForm(forms.ModelForm):
    class Meta:
        model = PitchDeck
        fields = ('pitch', 'industry', 'instagram', 'linkedin', 'website', 'twitter', 'facebook', 'youtube')
        # widgets = {
        #     'pitch': forms.Textarea(attrs={'rows': 6, 'placeholder': 'Pitch'}),
        #     'industry': forms.Select(attrs={'placeholder': 'Industry'}),
        #     'instagram': forms.TextInput(attrs={'placeholder': 'Instagram URL'}),
        #     'linkedin': forms.TextInput(attrs={'placeholder': 'LinkedIn URL'}),
        #     'website': forms.URLInput(attrs={'placeholder': 'Website URL'}),
        #     'twitter': forms.TextInput(attrs={'placeholder': 'Twitter URL'}),
        #     'facebook': forms.TextInput(attrs={'placeholder': 'Facebook URL'}),
        #     'youtube': forms.TextInput(attrs={'placeholder': 'YouTube URL'}),
        # }

jjltech/apps/pitchdeck/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from .models import PitchDeck
from .forms import PitchDeckForm
from django.db.models import Q
from django.core.paginator import Paginator
from django.http import JsonResponse
from django_countries import countries

# Options for Industry Choices
INDUSTRY_CHOICES = [
        ('tech', 'Technology'),
        ('finance', 'Finance'),
        ('health', 'Healthcare'),
        ('education', 'Education'),
        ('entertainment', 'Entertainment'),
        ('retail', 'Retail'),
        ('manufacturing', 'Manufacturing'),
        ('real_estate', 'Real Estate'),
        ('transportation', 'Transportation'),
        ('energy', 'Energy'),
        ('agriculture', 'Agriculture'),
        ('hospitality', 'Hospitality'),
        ('construction', 'Construction'),
        ('legal', 'Legal'),
        ('marketing', 'Marketing'),
        ('media', 'Media'),
        ('non_profit', 'Non-Profit'),
        ('sports', 'Sports'),
        ('telecommunications', 'Telecommunications'),
        ('utilities', 'Utilities'),
        ('other', 'Other'),
    ]


def create_pitch_view(request):
    if request.method == 'POST':
        form = PitchDeckForm(request.POST)
        if form.is_valid():
            pitch = form.save(commit=False)
            pitch.user = request.user
            pitch.save()
            return redirect('pitchdeck:detail')
    else:
        form = PitchDeckForm()
    return render(request, 'pitchdeck/create.html', {'form': form})

def edit_pitch_view(request):
    user = request.user
    pitch = PitchDeck.objects.filter(user=user).first()
    if request.method == 'POST':
        form = PitchDeckForm(request.POST, instance=pitch)
        if form.is_valid():
            pitch = form.save(commit=False)
            pitch.user = request.user
            pitch.save()
            return redirect('pitchdeck:detail')
    else:
        form = PitchDeckForm(instance=pitch)
    return render(request, 'pitchdeck/edit.html', {'form': form})

def pitchdeck_detail_view(request):
    user = request.user
    pitch = PitchDeck.objects.filter(user=user).first()
    return render(request, 'pitchdeck/detail.html', {'pitch': pitch})

def pitchdeck_board(request):
    # get country choices from the country fields module
    country_choices = countries
    # get industry choices from the PitchDeck model
    industry_choices = INDUSTRY_CHOICES
    pitchdecks = PitchDeck.objects.all()
    # get top pitches, pitches with highest likes
    top_pitches = pitchdecks.order_by('-likes')[:5]
    industry = request.GET.get('industry')
    country = request.GET.get('country')
    keywords = request.GET.get('keywords')

    if industry:
        pitchdecks = pitchdecks.filter(industry=industry)
    if country:
        pitchdecks = pitchdecks.filter(user__profile__country=country)
    if keywords:
        pitchdecks = pitchdecks.filter(
            Q(pitch__icontains=keywords)
        )

    # Paginate the pitchdecks
    paginator = Paginator(pitchdecks, 12)  # Show 12 pitches per page
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'country_choices': country_choices,
        'industry_choices': industry_choices,
        'top_pitches': top_pitches,
        'industry': industry,
        'country': country,
        'keywords': keywords,
    }
    return render(request, 'pitchdeck/pitchdeck_board.html', context)


def like_pitch(request, pitch_id):
    pitch = get_object_or_404(PitchDeck, id=pitch_id)
    if request.user in pitch.likes.all():
        pitch.likes.remove(request.user)
        liked = False
    else:
        pitch.likes.add(request.user)
        liked = True
    return JsonResponse({'liked': liked, 'likes_count': pitch.likes.count()})


def pitchdeck_view(request, pitch_id):
    pitch = get_object_or_404(PitchDeck, id=pitch_id)
    pitch.clicks += 1
    pitch.save()

    # Fetch similar pitches based on industry or country
    similar_pitches = PitchDeck.objects.filter(
        Q(industry=pitch.industry) | Q(user__profile__country=pitch.user.profile.country)
    ).exclude(id=pitch.id)[:5]  # Exclude the current pitch and limit to 5

    context = {
        'pitch': pitch,
        'similar_pitches': similar_pitches,
    }
    return render(request, 'pitchdeck/pitchdeck.html', context)

jjltech/apps/pitchdeck/templates/pitchdeck/create.html
{% extends "layouts/base.html" %}
{% load static %}
{% load pitch_filters %}

{% block title %} Create PitchDeck {% endblock %}

{% block content %}
<div class="container">
    <div class="row"></div>
        <div class="col-md-8 offset-md-2">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title"><i class="material-icons" style="font-size: 24px;">text_fields</i> Create PitchDeck</h4>
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="id_pitch">
                                <i class="material-icons" style="font-size: 16px; vertical-align: middle;">description</i> 
                                Pitch
                            </label>
                            {{ form.pitch|add_class:"form-control" }}
                        </div>
                        <div class="form-group">
                            <label for="id_industry">
                                <i class="material-icons" style="font-size: 16px; vertical-align: middle;">business</i> 
                                Industry
                            </label>
                            {{ form.industry|add_class:"form-control" }}
                        </div>
                        <div class="form-group">
                            <label for="id_instagram">
                                <i class="material-icons" style="font-size: 16px; vertical-align: middle;">camera_alt</i> 
                                Instagram URL
                            </label>
                            {{ form.instagram|add_class:"form-control" }}
                        </div>
                        <div class="form-group">
                            <label for="id_linkedin">
                                <i class="material-icons" style="font-size: 16px; vertical-align: middle;">business_center</i> 
                                LinkedIn URL
                            </label>
                            {{ form.linkedin|add_class:"form-control" }}
                        </div>
                        <div class="form-group">
                            <label for="id_website">
                                <i class="material-icons" style="font-size: 16px; vertical-align: middle;">public</i> 
                                Website URL
                            </label>
                            {{ form.website|add_class:"form-control" }}
                        </div>
                        <div class="form-group">
                            <label for="id_twitter">
                                <i class="material-icons" style="font-size: 16px; vertical-align: middle;">X</i> 
                                Twitter URL
                            </label>
                            {{ form.twitter|add_class:"form-control" }}
                        </div>
                        <div class="form-group">
                            <label for="id_facebook">
                                <i class="material-icons" style="font-size: 16px; vertical-align: middle;">facebook</i> 
                                Facebook URL
                            </label>
                            {{ form.facebook|add_class:"form-control" }}
                        </div>
                        <div class="form-group">
                            <label for="id_youtube">
                                <i class="material-icons" style="font-size: 16px; vertical-align: middle;">play_circle_filled</i> 
                                YouTube URL
                            </label>
                            {{ form.youtube|add_class:"form-control" }}
                        </div>
                        <button type="submit" class="btn btn-primary btn-block">
                            <i class="material-icons" style="font-size: 16px; vertical-align: middle;">check</i> 
                            Create PitchDeck
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

jjltech/apps/pitchdeck/templates/pitchdeck/detail.html
{% extends "layouts/base.html" %}
{% load static %}

{% block title %} PitchDeck Details {% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <div class="card">
        <div class="card-header">
          <h4 class="card-title">{{ pitch.user.username }}'s PitchDeck</h4>
        </div>
        <div class="card-body">
          <p><strong>Pitch:</strong> {{ pitch.pitch }}</p>
          <p><strong>Instagram:</strong> <a href="{{ pitch.instagram }}" target="_blank">{{ pitch.instagram }}</a></p>
          <p><strong>LinkedIn:</strong> <a href="{{ pitch.linkedin }}" target="_blank">{{ pitch.linkedin }}</a></p>
          <p><strong>Website:</strong> <a href="{{ pitch.website }}" target="_blank">{{ pitch.website }}</a></p>
          <p><strong>Twitter:</strong> <a href="{{ pitch.twitter }}" target="_blank">{{ pitch.twitter }}</a></p>
          <p><strong>Facebook:</strong> <a href="{{ pitch.facebook }}" target="_blank">{{ pitch.facebook }}</a></p>
          <p><strong>YouTube:</strong> <a href="{{ pitch.youtube }}" target="_blank">{{ pitch.youtube }}</a></p>
          <p><strong>Clicks:</strong> {{ pitch.clicks }}</p>
          <p><strong>Likes:</strong> {{ pitch.likes }}</p>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

jjltech/apps/pitchdeck/templates/pitchdeck/edit.html
{% extends "layouts/base.html" %}
{% load static %}
{% load pitch_filters %}

{% block title %} Edit PitchDeck {% endblock %}

{% block content %}
<div class="container">
    <div class="row"></div>
        <div class="col-md-8 offset-md-2">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title"><i class="material-icons" style="font-size: 24px;">text_fields</i> Create PitchDeck</h4>
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="id_pitch">
                                <i class="material-icons" style="font-size: 16px; vertical-align: middle;">description</i> 
                                Pitch
                            </label>
                            {{ form.pitch|add_class:"form-control" }}
                        </div>
                        <div class="form-group">
                            <label for="id_industry">
                                <i class="material-icons" style="font-size: 16px; vertical-align: middle;">business</i> 
                                Industry
                            </label>
                            {{ form.industry|add_class:"form-control" }}
                        </div>
                        <div class="form-group">
                            <label for="id_instagram">
                                <i class="material-icons" style="font-size: 16px; vertical-align: middle;">camera_alt</i> 
                                Instagram URL
                            </label>
                            {{ form.instagram|add_class:"form-control" }}
                        </div>
                        <div class="form-group">
                            <label for="id_linkedin">
                                <i class="material-icons" style="font-size: 16px; vertical-align: middle;">business_center</i> 
                                LinkedIn URL
                            </label>
                            {{ form.linkedin|add_class:"form-control" }}
                        </div>
                        <div class="form-group">
                            <label for="id_website">
                                <i class="material-icons" style="font-size: 16px; vertical-align: middle;">public</i> 
                                Website URL
                            </label>
                            {{ form.website|add_class:"form-control" }}
                        </div>
                        <div class="form-group">
                            <label for="id_twitter">
                                <i class="material-icons" style="font-size: 16px; vertical-align: middle;">X</i> 
                                Twitter URL
                            </label>
                            {{ form.twitter|add_class:"form-control" }}
                        </div>
                        <div class="form-group">
                            <label for="id_facebook">
                                <i class="material-icons" style="font-size: 16px; vertical-align: middle;">facebook</i> 
                                Facebook URL
                            </label>
                            {{ form.facebook|add_class:"form-control" }}
                        </div>
                        <div class="form-group">
                            <label for="id_youtube">
                                <i class="material-icons" style="font-size: 16px; vertical-align: middle;">play_circle_filled</i> 
                                YouTube URL
                            </label>
                            {{ form.youtube|add_class:"form-control" }}
                        </div>
                        <button type="submit" class="btn btn-primary btn-block">
                            <i class="material-icons" style="font-size: 16px; vertical-align: middle;">check</i> 
                            Save Changes
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

jjltech/apps/pitchdeck/templates/pitchdeck/pitchdeck.html
{% extends "layouts/board_base.html" %}
{% load static %}

{% block title %}{{ pitch.user.username }} - PitchDeck{% endblock %}

{% block styles %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600&display=swap" rel="stylesheet">

{% endblock %}


{% block content %}

<section class="pitch-detail py-5 bg-light" style="margin-top: 80px;"></section>
    <div class="container-fluid">
        <div class="row">
            <!-- Pitch Details -->
            <div class="col-lg-8">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <div class="d-flex align-items-start">
                            <img src="{{ pitch.user.profile.profile_image.url }}" alt="Pitch Image" class="rounded me-3" style="width: 150px; height: auto;">
                            <div>
                                <p class="text-muted"><i class="fas fa-briefcase"></i> <strong>Industry:</strong> {{ pitch.industry }}</p>
                                <p class="text-muted"><i class="fas fa-globe"></i> <strong>Country:</strong> {{ pitch.user.profile.country }}</p>
                                <p class="card-text"><i class="fas fa-comment"></i> {{ pitch.pitch }}</p>
                            </div>
                        </div>
                        <div class="d-flex justify-content-between align-items-center mt-4">
                            <button class="btn btn-outline-danger like-btn" data-id="{{ pitch.id }}">
                                <i class="fas fa-heart"></i> <span class="likes-count">{{ pitch.likes.count }}</span>
                            </button>
                            <span><i class="fas fa-eye"></i> {{ pitch.clicks }} Views</span>
                        </div>
                    </div>
                </div>
            </div>

            <!-- User Profile -->
            <div class="col-lg-4">
                <div class="card shadow-sm">
                    <div class="card-body text-center">
                        <img src="{{ pitch.user.profile.profile_image.url }}" alt="User Profile" class="rounded-circle mb-3" width="120" height="120">
                        <h4>@{{ pitch.user.username }}</h4>
                        <p class="text-muted">{{ pitch.user.profile.headline }}</p>
                        <div class="social-links mt-3">
                            {% if pitch.linkedin %}
                                <a href="{{ pitch.linkedin }}" class="btn btn-outline-primary btn-sm me-2"><i class="fab fa-linkedin"></i></a>
                            {% endif %}
                            {% if pitch.twitter %}
                                <a href="{{ pitch.twitter }}" class="btn btn-outline-info btn-sm me-2"><i class="fab fa-twitter"></i></a>
                            {% endif %}
                            {% if pitch.website %}
                                <a href="{{ pitch.website }}" class="btn btn-outline-dark btn-sm me-2"><i class="fas fa-globe"></i></a>
                            {% endif %}
                            {% if pitch.instagram %}
                                <a href="{{ pitch.instagram }}" class="btn btn-outline-danger btn-sm me-2"><i class="fab fa-instagram"></i></a>
                            {% endif %}
                            {% if pitch.facebook %}
                                <a href="{{ pitch.facebook }}" class="btn btn-outline-primary btn-sm me-2"><i class="fab fa-facebook"></i></a>
                            {% endif %}
                            {% if pitch.youtube %}
                                <a href="{{ pitch.youtube }}" class="btn btn-outline-danger btn-sm"><i class="fab fa-youtube"></i></a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Similar Pitches -->
        <div class="similar-pitches mt-5">
            <h3 class="mb-4">Similar Pitches</h3>
            <div class="row g-4">
                {% for similar_pitch in similar_pitches %}
                <div class="col-md-6 col-lg-4">
                    <div class="card shadow-sm">
                        <img src="{{ similar_pitch.user.profile.profile_image.url }}" alt="Similar Pitch" class="card-img-top">
                        <div class="card-body">
                            <h5 class="card-title">{{ similar_pitch.title }}</h5>
                            <p class="text-muted"><strong>Industry:</strong> {{ similar_pitch.industry }}</p>
                            <p class="text-muted"><strong>Country:</strong> {{ similar_pitch.user.profile.country }}</p>
                            <a href="{% url 'pitchdeck:pitchdeck_view' similar_pitch.id %}" class="btn btn-primary btn-sm">View Pitch</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</section>

<script>
    // Like button functionality
    document.querySelectorAll('.like-btn').forEach(button => {
        button.addEventListener('click', function () {
            const pitchId = this.getAttribute('data-id');
            fetch(`/pitchdeck/like/${pitchId}/`, { method: 'POST', headers: { 'X-CSRFToken': '{{ csrf_token }}' } })
                .then(response => response.json())
                .then(data => {
                    if (data.liked) {
                        this.classList.add('btn-danger');
                    } else {
                        this.classList.remove('btn-danger');
                    }
                    this.querySelector('.likes-count').textContent = data.likes_count;
                });
        });
    });
</script>
{% endblock %}